name: GitHub - Repository


on:
  push:
    branches:
    - main
    paths:
    - .github/labels.yaml
    - .github/workflows/github.repo.yaml

  pull_request:
    paths:
    - .github/labels.yaml
    - .github/workflows/github.repo.yaml

  workflow_dispatch: {}


jobs:
  sync-labels:
    name: Sync Labels
    uses: tedilabs/github-actions/.github/workflows/github.repo.sync-labels.yaml@main

    permissions:
      contents: read
      issues: write

    with:
      config_file: .github/labels.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
