name: Integration - YAML


on:
  push:
    branches:
    - main
    paths:
    - "**.yaml"
    - "**.yml"

  pull_request:
    paths:
    - "**.yaml"
    - "**.yml"

  workflow_dispatch: {}


concurrency:
  group: integration-yaml-${{ github.ref }}
  cancel-in-progress: true


jobs:
  lint:
    name: Lint (yamllint)
    uses: tedilabs/github-actions/.github/workflows/yaml.yamllint.yaml@main

    with:
      yamllint_version: latest
      yamllint_config_file: .yamllint.yaml
      yamllint_target_dir: ./
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
